Repository exercism/swift, pull requests merged in 2021-11, with the labels that each got.

#505 🤖 Remove obsolete `maintainers.json` file
  .github/CODEOWNERS
  config/maintainers.json
Labels: x:size/tiny

#503 🤖 Change difficulty `0` to `1`
  config.json
Labels: v3-migration 🤖, x:size/tiny

#499 Fix typo in vehicle-purchase exercise tests
  exercises/concept/vehicle-purchase/Tests/VehiclePurchaseTests/VehiclePurchaseTests.swift
Labels: x:size/small

#508 Added colons to amount tuple
  exercises/concept/lasagna-master/.docs/instructions.md
Labels: x:size/tiny

#509 Improved bad example in high-score-board introduction
  exercises/concept/high-score-board/.docs/introduction.md
Labels: x:size/tiny

#510 Added missing double quotes in instructions
  exercises/concept/master-mixologist/.docs/instructions.md
Labels: x:size/tiny

#511 Correction in first exercise
  exercises/concept/windowing-system/.docs/instructions.md
Labels: x:size/small

#512 [Characters Concept] Fix typo with full stop
  concepts/characters/introduction.md
Labels: x:size/tiny

#515 Have sample match expected output in tests
  exercises/concept/windowing-system/.docs/instructions.md
Labels: x:size/small

#514 Minor correction to instruction
  exercises/concept/poetry-club/.docs/instructions.md
Labels: x:size/small

#517 Fix typos in instructions.md and introduction.md
  exercises/concept/vehicle-purchase/.docs/instructions.md
  exercises/concept/vehicle-purchase/.docs/introduction.md
Labels: x:size/tiny
