Repository exercism/swift, pull requests merged in 2023-07, with the labels that each got.

#626 [Installation.md]: Update & updated formatting
  docs/INSTALLATION.md
  exercises/concept/poetry-club/.docs/instructions.md
  exercises/concept/poetry-club/.meta/Sources/PoetryClub/PoetryClubExemplar.swift
  exercises/concept/poetry-club/Sources/PoetryClub/PoetryClub.swift
  exercises/concept/poetry-club/Tests/PoetryClubTests/PoetryClubTests.swift
Labels: x:rep/small

#627 [Key-features]: Update information
  config.json
Labels: x:rep/tiny

#643 Convert `average_run_time` to an integer
  config.json
Labels: x:size/tiny

#646 Fix typo Aannotations > Annotations in link name
  concepts/function-overloading/links.json
Labels: x:rep/small

#648 [Generator]: Initial implimentation
  .github/workflows/ci.yml
  bin/test_generator.sh
  generator/Package.swift
  generator/Sources/Generator/generator-help.swift
  generator/Sources/Generator/generator-plugins.swift
  generator/Sources/Generator/main.swift
  generator/Tests/GeneratorTests/GeneratorTests.swift
  generator/Tests/GeneratorTests/files/all-test-removed/.meta/tests.toml
  generator/Tests/GeneratorTests/files/all-tests-included/.meta/tests.toml
  generator/Tests/GeneratorTests/files/two-tests-removed/.meta/tests.toml
  generator/readme.md
Labels: x:rep/massive
